Added options -c -v -h
mklement0/ttab pull request #72
Opened 2024-05-20 10:26 UTC by HofiOne

- `-c`    Do not open any new window or tab, run in the current tab of the current window.
- `-v`    Open new split tab vertically in the current window.
- `-h`    Open new split tab horizontally in the current window.

2024-05-21 21:44 UTC, mklement0 commented
This looks very promising, thank you.

Some high-level questions / comments first:

* What is the value of the `-c` option? why wouldn't you just execute a command directly, or, if you were targeting a different terminal app with `-a` (from Terminal to iTerm, say), why would you want to execute something in the _current_ tab in the other app?
  * (As an aside: `-c` is currently broken in Terminal.app)

* Rather than _documenting_ incompatible or ignored options, I prefer them to be prevented programmatically:
  * If `-g` / `-G` cannot be meaningfully combined with `-h` or `-v`, a syntax error should be reported.
  * Also, specifying _both_ `-h` and `-v` should be prevented.

* In the synopsis part of the embedded man page, the description of iTerm-only options (`-h`, `-v`) should have an "iTerm only:" prefix.

* In the remainder of the embedded man page, please restore the two trailing spaces at the end of all lines, which are meant to ensure word wrapping for proper rendering in an 80-column terminal.

* There are typos: `Schortcuts` -> `Shortcuts`, `un-priviliged` -> `un-privileged`, or perhaps  better: `non-privileged`; also, I prefer not to use the word "the" in "via the environment variable TTAB_CMD_DELAY"

2024-05-22 08:55 UTC, HofiOne commented
>     also, I prefer not to use the word "the" in "via the environment variable TTAB_CMD_DELAY"

Sorry, i could not find any related changes by me around the word `TTAB_CMD_DELAY`
Could you please add a comment on this in the [review part](https://github.com/mklement0/ttab/pull/72/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

2024-05-22 11:30 UTC, HofiOne commented
I hope I addressed now all of your concerns, please check them, also please use the GitHub [review tool](https://github.com/mklement0/ttab/pull/72/files) in case of any further comments as it is much easier to handle, and follow them one by one over there.
Thank you!

2024-05-22 16:11 UTC, mklement0 requested changes
First things first: I greatly appreciate the effort you've put into this.

There's quite a few changes I'm requesting, but most of them are minor. I do wonder if we need the `-n` option, however.

2024-05-22 16:54 UTC, HofiOne commented on bin/ttab
> + * `-n <name>`
Here you can see 2 cases

![Screenshot 2024-05-22 at 18 49 28](https://github.com/mklement0/ttab/assets/12213492/cc2139d7-ed5b-45d6-a7f5-e36c382a84bf)
![Screenshot 2024-05-22 at 18 49 59](https://github.com/mklement0/ttab/assets/12213492/512b6d62-c36d-4ba2-a28b-a7880fd36212)

the 2nd one is the worst, the UUID name suppresses the whole, useful part of the error message

I did not want to hardcode it, but as you wish, we can do so of course

2024-05-22 17:13 UTC, mklement0 commented on bin/ttab
> + * `-n <name>`
Got it. Yes, let's hard-code the name, to keep things simple.

2024-05-22 19:49 UTC, HofiOne commented
> There's quite a few changes I'm requesting, but most of them are minor. I do wonder if we need the `-n` option, however.

Hope I did not forget anything, please feel free to add further comments if needed.

2024-05-22 20:20 UTC, mklement0 approved these changes
There's a minor typo (`tterm` instead of `ttab`), but otherwise this looks great. I'll deal with the typo, as I'm planning on adding another check anyway.

2024-05-22 20:22 UTC, merged

2024-05-22 20:29 UTC, HofiOne commented
> There's a minor typo (`tterm` instead of `ttab`), but otherwise this looks great. I'll deal with the typo, as I'm planning on adding another check anyway.

Ahhh, shame on me, will you fix it, or should I send a new fix PR?

2024-05-22 20:56 UTC, mklement0 commented
I'll fix it myself, thanks, and thanks again for your contribution.

I'll try to release a new version soon.

2024-05-22 23:39 UTC, HofiOne commented
Oh, one more issue, sorry :(
Probably you noticed too.

in line 398 of ttab

  elif (( gnomeTerminal && inCurrent ))

must be

  elif (( gnomeTerminal && inCurrent )); then

2024-05-22 23:46 UTC, mklement0 commented
No worries; already fixed. v0.9.0 has now been published.

2024-05-23 01:03 UTC, HofiOne commented
perfect, thank you!

2024-05-23 08:43 UTC, HofiOne commented
btw, you might want to close this one as well
https://github.com/mklement0/ttab/issues/18
cheers!